FROM python:3.11-slim

WORKDIR /app

# Install OS dependencies needed for OpenCV or other scientific libs
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && apt-get clean

# Copy application code
COPY . /app

# Install Python dependencies
RUN pip install -r requirements.txt

# The main entrypoint for the edge server
CMD ["python", "server.py"]
